language: csharp
mono: latest
sudo: false
dotnet: 3.0
dist: bionic

before_install:
  - sudo apt-get install -y dotnet-runtime-2.2

install:
- nuget install NUnit.Console -Version 3.10.0 -OutputDirectory testrunner
script:
- nuget restore SharpMap.Extensions/packages.config -o packages
- dotnet msbuild SharpMap.targets /t:Version /p:UseTools35=false /v:minimal
- dotnet msbuild SharpMap.sln /m "/t:Restore;Build" /p:Configuration=ReleaseLinux "/p:Platform=Any CPU" /p:UseTools35=false "/p:FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/" /v:minimal /p:WarningLevel=3
- pushd UnitTests/bin/ReleaseLinux/net472
- mono ../../../../testrunner/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe --where "cat != RequiresWindows" UnitTests.dll
- popd
